name: analyze-images

channels:
    - default
    - conda-forge

dependencies:
    - python=3.8.11
    - numpy
    - scipy
    - scikit-image
    - pandas
    - matplotlib
    - jupyterlab>=3
    - ipywidgets
    - pycodestyle
    - pydocstyle
    - pylint
    - plotly